EduMS/urls.py
# 注意所有app的url都要加载到这里
# 即通过include加到path里

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse, redirect


def index(request):
    # 主页，跳转到ems主页
    return redirect(reverse('ems:index'))

urlpatterns = [
    path('admin/', admin.site.urls),  # 管理页面
    path('', index),  # 主页
    path('user/', include('user.urls', namespace='user')),
    path('bbs/', include('bbs.urls', namespace='bbs')),
    path('ems/', include('ems.urls', namespace='ems')),
]

bbs/urls.py
from django.urls import path

from . import views

app_name = 'bbs'
urlpatterns = [
    path('', views.index, name='index'), # 首页
    path('article/<int:page>/', views.article, name='article'),  # 文章列表
    path('publish', views.PublishView.as_view(), name='publish'),  # 发表文章
    path('detail/<int:id>/', views.detail, name='detail'),  # 文章详情
    path('comment/<int:id>/', views.comment, name='comment'),  # 发表评论
]

ems/urls.py
from django.urls import path

from . import views

app_name = 'ems'
urlpatterns = [
    path('', views.index, name='index'),  # 主页
    path('relate/', views.RelateView.as_view(), name='relate'),  # 关联学号/工号
    path('grade/', views.grade_student, name='grade_student'),  # 成绩，学生
    path('grade/<int:subject_id>/', views.GradeTeacherView.as_view(), name='grade_teacher'),  # 成绩，老师
    path('subject/', views.subject, name='subject_teacher'),  # 课程选择
]

user/urls.py
# 设置url路径
# 也就是设置网页访问url时对应的处理函数
# 详情可以点进函数里边去看
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),  # 用户主页
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('modify/<str:item>', views.ModifyView.as_view(), name='modify'),  # 修改信息或密码
    path('logout/', views.logout, name='logout'),  # 注销
    path('captcha/', views.graph_captcha, name='captcha'),  # 验证码
    path('getpassword/', views.GetPasswordView.as_view(), name='getPassword'),  # 验证码
]

bbs/models.py
from django.db import models
from user.models import User
from datetime import datetime


class Article(models.Model):
    # 文章表
    # 注意作者为某个user（而非student或teacher）
    title = models.CharField(max_length=30, verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    publish_time = models.DateTimeField(default=datetime.now, verbose_name='发表时间')
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'


class Comment(models.Model):
    # 文章表
    # 注意作者为某个user（而非student或teacher）
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    content = models.CharField(max_length=300, verbose_name='内容')
    publish_time = models.DateTimeField(default=datetime.now, verbose_name='发表时间')
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论'

bbs/forms.py
from django.forms import Form, CharField


class ArticleForm(Form):
    # 文章验证表单
    title = CharField(required=True, max_length=30, error_messages={
        'required': '请输入标题！',
        'max_length': '输入的标题过长（超过30个字符）！',
    })
    content = CharField(required=True, error_messages={
        'required': '请输入一些内容！',
    })

bbs/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View
from django.views.decorators.http import require_POST
from .utils import login_required
from django.utils.decorators import method_decorator
from .models import Article, Comment
from .parameters import CURRENT_USER
from .forms import ArticleForm
from django.core.paginator import Paginator, EmptyPage


@login_required
def index(request, **kwargs):
    # 主页，直接跳转到文章列表的第一页
    return redirect(reverse('bbs:article', kwargs={'page': 1}))


@method_decorator(login_required, name='dispatch')
class PublishView(View):
    # 发表文章

    # get方法，直接渲染页面，传入error_message
    def get(self, request, error_message=None, **kwargs):
        if error_message:
            context = {
                'error_message': error_message
            }
        else:
            context = {}
        return render(request, 'bbs/publish.html', context=context)

    # post方法，处理用户提交的文章信息，根据处理结果做不同的返回
    def post(self, request, **kwargs):
        form = ArticleForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            author = kwargs.get(CURRENT_USER)
            article = Article(title=title, content=content, author=author)
            article.save()
            return self.get(request, error_message='发表成功！')
        else:
            error_message = form.errors.popitem()[1][0]
            return self.get(request, error_message)


@login_required
def article(request, page, **kwargs):
    # 文章列表
    articles = Article.objects.all().order_by('-publish_time')  # 取出所有文章，按照发表时间排列（新到旧）
    # 下面是django分页的一些设置，基本都是固定的
    paginator = Paginator(articles, 10)  # 设置每一页显示几条  创建一个panginator对象

    try:
        current_num = page
        if not current_num: current_num=1# 当你在url内输入的?page = 页码数  显示你输入的页面数目 默认为第1页
        articles = paginator.page(current_num)
    except EmptyPage:
        return redirect(reverse('bbs:article', kwargs={'page': 1})) # 当你输入的page是不存在的时候跳转到第1页

    if paginator.num_pages > 11:  # 如果分页的数目大于11
        if current_num - 5 < 1:  # 你输入的值
            pageRange = range(1, 11)  # 按钮数
        elif current_num + 5 > paginator.num_pages:  # 按钮数加5大于分页数
            pageRange = range(current_num - 5, current_num + 1)  # 显示的按钮数

        else:
            pageRange = range(current_num - 5, current_num + 6)  # range求的是按钮数   如果你的按钮数小于分页数 那么就按照正常的分页数目来显示

    else:
        pageRange = paginator.page_range  # 正常分配

    context = {
        'articles': articles,
        'pageRange': pageRange,
    }
    return render(request, 'bbs/article.html', context=context)


@login_required
def detail(request, id, **kwargs):
    # 文章详情页面
    # 根据文章ID（从url中获取）获取文章以及其所有评论
    article = get_object_or_404(Article, pk=id)
    comments = article.comment_set.all().order_by('-publish_time')
    context = {
        'article': article,
        'comments': comments,
    }
    return render(request, 'bbs/detail.html', context=context)


@login_required
@require_POST
def comment(request, id, **kwargs):
    # 发表评论（展示评论在文章详情页中）
    # 根据文章ID（从url中获取）获取针对的文章
    # 获取request中的评论内容，存入数据库中即可
    article = get_object_or_404(Article, pk=id)
    current_user = kwargs.get(CURRENT_USER)
    comment_content = request.POST['commentContent']
    comment = Comment(article=article, content=comment_content, author=current_user)
    comment.save()
    # 添加完成后返回当前文章详情界面
    return redirect(reverse('bbs:detail', kwargs={'id':id}))

bbs/templates/bbs/_head.html
<meta charset="UTF-8">
{% load static %}
<script src="{% static 'user/jquery.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="{% static 'user/bootstrap/bootstrap.min.js' %}"></script>

bbs/templates/bbs/article.html
{% extends 'bbs/base.html' %}

{% block title %}
    文章浏览
{% endblock %}

{% block more_head %}
    {% load static %}
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading"><h1>文章浏览</h1></div>
        <div class="panel-body">
            <ul class="article-list" id="articles">
                {% for article in articles %}
                    <li>
                        <a href="{% url 'bbs:detail' id=article.id %}">{{ article.title }}</a>
                        <span>{{ article.publish_time }}</span><span>{{ article.author.username }}</span>
                    </li>
                {% endfor %}
            </ul>
            <nav style="margin-left: 20px">
                <ul class="pagination">
                    {% for i in pageRange %}
                        {% if current_num == i %}
                            <li class="active"><a href="{% url 'bbs:article' page=i %}">{{ i }}</a></li>
                        {% else %}
                            <li><a href="{% url 'bbs:article' page=i %}">{{ i }}</a></li>
                        {% endif %}


                    {% endfor %}
                </ul>
            </nav>

        </div>
    </div>
{% endblock %}

bbs/templates/bbs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "bbs/_head.html" %}
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bbs/css/base.css' %}">
    {% block more_head %}{% endblock %}
</head>
<body>
    <div class="top">
        <div class="logo-box">
            <img src="{% static 'bbs/imgs/university-logo.png' %}" alt="加载中...">
            <img src="{% static 'bbs/imgs/ems-logo.png' %}" alt="加载中...">
        </div>
        <div class="operation-box">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <a href="{% url 'ems:index' %}">{{ current_user }}</a>
            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
            <a href="{% url 'user:logout' %}">注销</a>
        </div>
    </div>
    <div class="mid">
        <div class="left">
            <div class="list-group">
                <a href="{% url 'ems:index' %}" class="list-group-item" style="margin-bottom: 20px">首页</a>
                <li class="list-group-item list-group-item-success">
                    个人中心
                </li>
                <a href="{% url 'user:modify' item='info' %}" class="list-group-item">修改信息</a>
                <a href="{% url 'user:modify' item='password' %}" class="list-group-item">修改密码</a>
            </div>
            <div class="list-group">
                <li class="list-group-item list-group-item-success">
                    教务中心
                </li>
                {% if current_user.role.name == '教师' %}
                <a href="{% url 'ems:relate' %}" class="list-group-item">关联工号</a>
                <a href="{% url 'ems:subject_teacher' %}" class="list-group-item">录入成绩</a>
                {% else %}
                <a href="{% url 'ems:relate' %}" class="list-group-item">关联学号</a>
                <a href="{% url 'ems:grade_student' %}" class="list-group-item">查询成绩</a>
                {% endif %}
            </div>
            <div class="list-group">
                <li class="list-group-item list-group-item-success">
                    互动中心
                </li>
                <a href="{% url 'bbs:publish' %}" class="list-group-item">发表文章</a>
                <a href="{% url 'bbs:article' page=1 %}" class="list-group-item">浏览文章</a>
            </div>
        </div>
        <div class="right">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

bbs/templates/bbs/detail.html
{% extends 'bbs/base.html' %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block more_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bbs/css/detail.css' %}">
{% endblock %}

{% block content %}
    <div class="article-container">
        <h2>{{ article.title }}</h2>
        <p class="article-info-group">
            <span>发表时间：{{ article.publish_time }}</span>
            <span>作者：{{ article.author.username }}</span>
        </p>
        <article class="article-content" id="article-content" data-id="{{ article.id }}">
            {{ article.content|safe }}
        </article>
    </div>
    <div class="comment-group">
    <div class="panel panel-default">
        <div class="panel-heading">评论列表</div>
        <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    <p class="comment-info">
                        <span>{{ comment.author.username }}</span>
                        <span>{{ comment.publish_time }}</span>
                    </p>
                    <p class="comment-content">
                        <span>{{ comment.content | safe }}</span>
                    </p>
                </li>
            {% endfor %}
        </ul>
    </div>
    </div>
    <div class="add-comment-group">
        <h3>发表评论</h3>
        <form action="{% url 'bbs:comment' id=article.id %}" method="post">
            {% csrf_token %}
            <textarea class="form-control" name="commentContent" rows="3"></textarea>
            <input type="submit" value="发表评论" class="comment-submit">
        </form>

    </div>

{% endblock %}

bbs/templates/bbs/publish.html
{% extends 'bbs/base.html' %}

{% block title %}
    发表文章
{% endblock %}

{% block more_head %}
    {% load static %}
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading"><h1>发表文章</h1></div>
        <div class="panel-body">
            <p class="error_message">{{ error_message }}</p>
            <form class="form-horizontal" action="{% url 'bbs:publish' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputTitle" class="col-sm-1 control-label">标题</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputTitle" name="title" placeholder="请输入标题">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputContent" class="col-sm-1 control-label">内容</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="inputContent" name="content" placeholder="请输入内容" rows="10"></textarea>
                    </div>
                <input type="submit" value="立即发表" class="btn btn-primary" style="margin-top: 20px;margin-left: 100px">
                </div>
            </form>
        </div>
    </div>
{% endblock %}