EduMS/urls.py
# 注意所有app的url都要加载到这里
# 即通过include加到path里

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse, redirect


def index(request):
    # 主页，跳转到ems主页
    return redirect(reverse('ems:index'))

urlpatterns = [
    path('admin/', admin.site.urls),  # 管理页面
    path('', index),  # 主页
    path('user/', include('user.urls', namespace='user')),
    path('bbs/', include('bbs.urls', namespace='bbs')),
    path('ems/', include('ems.urls', namespace='ems')),
]

bbs/urls.py
from django.urls import path

from . import views

app_name = 'bbs'
urlpatterns = [
    path('', views.index, name='index'), # 首页
    path('article/<int:page>/', views.article, name='article'),  # 文章列表
    path('publish', views.PublishView.as_view(), name='publish'),  # 发表文章
    path('detail/<int:id>/', views.detail, name='detail'),  # 文章详情
    path('comment/<int:id>/', views.comment, name='comment'),  # 发表评论
]

ems/urls.py
from django.urls import path

from . import views

app_name = 'ems'
urlpatterns = [
    path('', views.index, name='index'),  # 主页
    path('relate/', views.RelateView.as_view(), name='relate'),  # 关联学号/工号
    path('grade/', views.grade_student, name='grade_student'),  # 成绩，学生
    path('grade/<int:subject_id>/', views.GradeTeacherView.as_view(), name='grade_teacher'),  # 成绩，老师
    path('subject/', views.subject, name='subject_teacher'),  # 课程选择
]

user/urls.py
# 设置url路径
# 也就是设置网页访问url时对应的处理函数
# 详情可以点进函数里边去看
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),  # 用户主页
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('modify/<str:item>', views.ModifyView.as_view(), name='modify'),  # 修改信息或密码
    path('logout/', views.logout, name='logout'),  # 注销
    path('captcha/', views.graph_captcha, name='captcha'),  # 验证码
    path('getpassword/', views.GetPasswordView.as_view(), name='getPassword'),  # 验证码
]

ems/models.py
from django.db import models
# 注意这里从其他app引入model的方式，正常python不支持这样的导入，但是django里边采用这种方法  创建数据库
from user.models import User


GENDER_LIST = ((1, '男'), (-1, '女'))

class Student(models.Model):
    # 学生
    # 注意user：与学生为一对一关系，可以为空（当一个学生信息没有绑定到任何用户的时候）
    s_id = models.IntegerField(primary_key=True, verbose_name='学号')
    real_name = models.CharField(max_length=10, verbose_name='姓名')
    gender = models.IntegerField(choices=GENDER_LIST, default=1, verbose_name='性别')
    user = models.OneToOneField(User, on_delete=models.SET_NULL, verbose_name='用户', null=True, blank=True)
    password = models.CharField(max_length=10, verbose_name='校园卡密码')

    def __str__(self):
        return '{} {}'.format(self.s_id, self.real_name)

    class Meta:
        verbose_name = '学生'
        verbose_name_plural = '学生'


class Teacher(models.Model):
    # 教师
    # 注意user：与教师为一对一关系，可以为空（当一个教师信息没有绑定到任何用户的时候）
    t_id = models.IntegerField(primary_key=True, verbose_name='工号')
    real_name = models.CharField(max_length=10, verbose_name='姓名')
    gender = models.IntegerField(choices=GENDER_LIST, default=1, verbose_name='性别')
    user = models.OneToOneField(User, on_delete=models.SET_NULL, verbose_name='用户', null=True, blank=True)
    password = models.CharField(max_length=10, verbose_name='校园卡密码')


    def __str__(self):
        return '{} {}'.format(self.t_id, self.real_name)

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = '教师'


class Term(models.Model):
    # 学期
    # 注意名字必须唯一
    # 包含一个开始日期和一个结束日期
    name = models.CharField(max_length=20, verbose_name='名称', unique=True)
    start_date = models.DateField(verbose_name='开始日期')
    end_date = models.DateField(verbose_name='结束日期')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '学期'
        verbose_name_plural = '学期'


class Subject(models.Model):
    # 课程
    # 注意与老师和学期都为一对多关系（一个老师可以教多门课，一个学期可以有多门课，但反过来都是唯一的）
    # 注意与学生为多对多关系（一个课程里有多个学生，一个学生可以有很多课）
    id = models.IntegerField(primary_key=True, verbose_name='课程号')
    name = models.CharField(max_length=20, verbose_name='课程名')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name='任课教师')
    term = models.ForeignKey(Term, on_delete=models.CASCADE, verbose_name='开课学期')
    student = models.ManyToManyField(Student, verbose_name='学生')
    credit = models.FloatField(verbose_name='学分')

    def __str__(self):
        return '{} {}'.format(self.id, self.name)

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = '课程'


class Grade(models.Model):
    # 成绩
    # 即某一个课程上某一个学生的分数
    point = models.FloatField(verbose_name='分数')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name='课程')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='学生')

    def __str__(self):
        return '{} {} {}'.format(self.student.real_name, self.subject.name, self.point)

    class Meta:
        verbose_name = '成绩'
        verbose_name_plural = '成绩'
        # 注意这里student和subject的联合值应该是唯一的
        # 即一个学生在一个课程上的分数只有一个，二者构成联合主键
        unique_together = (("student", "subject"),)

ems/forms.py
from django.forms import Form, CharField, IntegerField


class RelateForm(Form):
    # 关联验证表单
    id = IntegerField(required=True, error_messages={
        'required': '请输入学号或工号！',
    })
    password = CharField(max_length=10, required=True, error_messages={
        'max_length': '输入的校园卡密码过长（超过10个字符）！',
        'required': '请输入校园卡密码！',
    })

ems/views.py
from django.shortcuts import render, HttpResponse, reverse, redirect, get_object_or_404
from django.views import View
from .utils import login_required, relate, search_grade, relate_required, success, server_error, params_error
from .parameters import CURRENT_USER
from .forms import RelateForm
from django.utils.decorators import method_decorator
from .models import Grade, Term, Subject, Student
import json
from django.core.paginator import Paginator, EmptyPage

@login_required
def index(request, **kwargs):
    # 主页，直接渲染html
    return render(request, 'ems/index.html')


@method_decorator(login_required, name='dispatch')
class RelateView(View):
    # 关联

    # get方法，直接渲染页面，传入error_message
    def get(self, request, error_message=None, **kwargs):
        if not error_message:
            error_message = request.GET.get('error_message')
        if error_message:
            context = {
                'error_message': error_message
            }
        else:
            context = {}
        return render(request, 'ems/relate.html', context=context)

    # post方法，处理用户提交的关联信息，根据处理结果做不同的返回
    def post(self, request, **kwargs):
        form = RelateForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data['id']
            password = form.cleaned_data['password']
            result = relate(request, id, password)  # 关联，参看relate
            if result['code'] == 200:
                return self.get(request, error_message=result.get('message'))
            else:
                error_message= result['message']
                return self.get(request, error_message)
        else:
            error_message = form.errors.popitem()[1][0]
            return self.get(request, error_message=error_message)


@method_decorator(login_required, name='dispatch')
@method_decorator(relate_required, name='dispatch')
class GradeTeacherView(View):
    # 成绩

    # get方法，渲染页面，传入error_message
    def get(self, request, subject_id, error_message=None, **kwargs):
        current_user = kwargs.get(CURRENT_USER)
        subject = get_object_or_404(Subject, pk=subject_id)
        context = {
            'subject': subject,
            'error_message': error_message,
        }
        if current_user.role.name == '教师':
            # 先验证登录的人是不是教师
            if subject.teacher == current_user.teacher:
                # 验证教师是否教这门课
                students = subject.student.all()
                for student in students:
                    grade = Grade.objects.filter(student=student).filter(subject=subject).first()
                    student.grade = grade
                context['students'] = students
                if error_message:
                    context['error_message'] = error_message
                return render(request, 'ems/grade_teacher.html', context=context)

            else:
                return redirect(reverse('subject_teacher'))
        else:
            return redirect(reverse('grade_student'))


    # post方法，处理用户提交的成绩信息，根据处理结果做不同的返回
    # 用于教师给学生录入或修改成绩
    # 前端会把成绩的id和更新后的分数一一配对传过来（points）
    # points结构： [{成绩id：更新后的成绩分数}, {同}, ...]
    def post(self, request, subject_id, **kwargs):
        error_message = None
        points = request.POST.getlist('point') # 获取分数列表
        grades = request.POST.getlist('grade') # 获取成绩id列表
        for i in range(len(grades)):
            # 遍历获取所有的配对值（成绩id-分数）
            # 根据成绩id，找出对应的成绩，修改分数，保存到数据库

            grade_id = grades[i]
            try:
                point = float(points[i])
                if point<0 or point>100:
                    error_message = '小于0或大于100的分数不会被更改！'
                else:
                    grade = get_object_or_404(Grade, pk=grade_id)
                    grade.point = point
                    grade.save()
            except:
                error_message = '提交过程出现错误，请检查输入是否合理！'
                return self.get(request, subject_id, error_message=error_message, **kwargs)
        return self.get(request, subject_id, error_message=error_message, **kwargs)


@login_required
@relate_required
def subject(request, **kwargs):
    # 课程列表页
    current_user = kwargs.get(CURRENT_USER)
    if current_user.role.name == '教师':
        # 筛选出登录教师执教的所有课程
        subjects = Subject.objects.all().filter(teacher=current_user.teacher)
        context = {
            'subjects': subjects
        }
        return render(request, 'ems/subject_teacher.html', context)
    else:
        return redirect(reverse('ems:grade_student'))


@login_required
@relate_required
def grade_student(request, **kwargs):
    # 学生成绩查询界面
    # 注意筛选条件也属于get方法（没有写入数据，只是筛选了获得的数据）
    # 前端会传入term， subject等数据，根据它们进行筛选，参看search_grade
    current_user = kwargs.get(CURRENT_USER)
    term_id = request.GET.get('term')
    subject_id = request.GET.get('subject')
    if term_id:
        term = Term.objects.get(id=term_id)
    else:
        term = None
    if subject_id:
        subject = Subject.objects.get(id=subject_id)
    else:
        subject = None
    grades = search_grade(request, term, subject)
    terms = Term.objects.all()  # 取出所有的学期传入前端以便前端选择
    subjects = Subject.objects.all()  # 取出所有的课程传入前端以便前端选择

    context = {
        'grades': grades,
        'terms': terms,
        'subjects': subjects,
    }

    if current_user.role.name == '学生':
        student = current_user.student
        context['student'] = student
        return render(request, 'ems/grade_student.html', context)
    else:
        return redirect(reverse('ems:subject_teacher'))

ems/templates/ems/_head.html
<meta charset="UTF-8">
{% load static %}
<script src="{% static 'user/jquery.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="{% static 'user/bootstrap/bootstrap.min.js' %}"></script>

ems/templates/ems/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "bbs/_head.html" %}
    {% load static %}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bbs/css/base.css' %}">
    {% block more_head %}{% endblock %}
</head>
<body>
    <div class="top">
        <div class="logo-box">
            <img src="{% static 'bbs/imgs/university-logo.png' %}" alt="加载中...">
            <img src="{% static 'bbs/imgs/ems-logo.png' %}" alt="加载中...">
        </div>
        <div class="operation-box">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <a href="{% url 'ems:index' %}">{{ current_user }}</a>
            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
            <a href="{% url 'user:logout' %}">注销</a>
        </div>
    </div>
    <div class="mid">
        <div class="left">
            <div class="list-group">
                <a href="{% url 'ems:index' %}" class="list-group-item" style="margin-bottom: 20px">首页</a>
                <li class="list-group-item list-group-item-success">
                    个人中心
                </li>
                <a href="{% url 'user:modify' item='info' %}" class="list-group-item">修改信息</a>
                <a href="{% url 'user:modify' item='password' %}" class="list-group-item">修改密码</a>
            </div>
            <div class="list-group">
                <li class="list-group-item list-group-item-success">
                    教务中心
                </li>
                {% if current_user.role.name == '教师' %}
                <a href="{% url 'ems:relate' %}" class="list-group-item">关联工号</a>
                <a href="{% url 'ems:subject_teacher' %}" class="list-group-item">录入成绩</a>
                {% else %}
                <a href="{% url 'ems:relate' %}" class="list-group-item">关联学号</a>
                <a href="{% url 'ems:grade_student' %}" class="list-group-item">查询成绩</a>
                {% endif %}
            </div>
            <div class="list-group">
                <li class="list-group-item list-group-item-success">
                    互动中心
                </li>
                <a href="{% url 'bbs:publish' %}" class="list-group-item">发表文章</a>
                <a href="{% url 'bbs:article' page=1 %}" class="list-group-item">浏览文章</a>
            </div>
        </div>
        <div class="right">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>
</html>

ems/templates/ems/grade_student.html
{% extends 'ems/base.html' %}

{% block title %}
    成绩查询
{% endblock %}

{% block more_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'ems/css/grade.css' %}">
    <script src="{% static 'ems/js/grade.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading"><h1>成绩查询</h1></div>
        <div class="panel-body">
            <div class="filter-box">
                <div class="input-group">
                    <span>查询条件：</span>
                    <form class="filter-form" action="{% url 'ems:grade_student' %}" method="get">
                        <div class="input-group term-filter">
                            <span class="input-group-addon" id="term-addon">学期：</span>
                            <select class="form-control" aria-describedby="term-addon" name="term">
                                <option value="">全部</option>
                                {% for term in terms %}
                                    <option value="{{ term.id }}">{{ term.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="input-group subject-filter">
                            <span class="input-group-addon" id="subject-addon">课程：</span>
                            <select class="form-control" aria-describedby="subject-addon" name="subject">
                                <option value="">全部</option>
                                {% for subject in subjects %}
                                    <option value="{{ subject.id }}">{{ subject.id }} {{ subject.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <input type="submit" value="提交查询" class="btn btn-primary">
                    </form>
                </div>
            </div>
            <div class="grade-table">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>姓名</th>
                        <th>学号</th>
                        {% for grade in grades %}
                            <th>{{ grade.subject.name }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ student.real_name }}</td>
                            <td>{{ student.s_id }}</td>
                            {% for grade in grades %}
                            <td>{{ grade.point }}</td>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

ems/templates/ems/grade_teacher.html
{% extends 'ems/base.html' %}

{% block title %}
    成绩录入
{% endblock %}

{% block more_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'ems/css/grade.css' %}">
    <script src="{% static 'ems/js/grade.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading"><h1>成绩录入</h1></div>
        <div class="panel-body">
        {% if error_message %}
        <p class="error_message">{{ error_message }}</p>
        {% endif %}
            <form action="{% url 'ems:grade_teacher' subject_id=subject.id %}" method="post">
            {% csrf_token %}
                <div class="grade-table">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>姓名</th>
                        <th>学号</th>
                        <th>分数</th>
                        <th>课程</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in students %}
                        <tr>
                            <td>{{ student.real_name }}</td>
                            <td>{{ student.s_id }}</td>
                            <td><input type="text" name="point" value="{{ student.grade.point }}"></td>
                            <td>{{ subject.name }}</td>
                            <input type="hidden" value="{{ student.grade.id }}" name="grade">
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
                <input type="submit" value="提交成绩" class="btn btn-default">
            </form>
        </div>
    </div>
{% endblock %}

ems/templates/ems/index.html
{% extends 'ems/base.html' %}

{% block title %}
    首页
{% endblock %}

{% block more_head %}
    {% load static %}
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading"><h1>主页</h1></div>
        <div class="panel-body">
            <h2>欢迎登录</h2>
            <img src="{% static 'ems/imgs/left.png' %}" alt="加载中...">
        </div>
    </div>
{% endblock %}

ems/templates/ems/relate.html
{% extends 'ems/base.html' %}

{% block title %}
    {% if current_user.role.name == '教师' %}
        关联工号
    {% else %}
        关联学号
    {% endif %}
{% endblock %}

{% block more_head %}
    {% load static %}
    <style>
        form {
            margin-top: 40px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        {% if current_user.role.name == '教师' %}
        <div class="panel-heading"><h1>关联工号</h1></div>
        <div class="panel-body">
            {% if current_user.teacher %}
                <h3>你已绑定至如下信息，如需解绑，请联系管理员</h3>
                <form>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>  工号
                        <input class="form-control" type="text" value="{{ current_user.teacher.t_id }}"
                               readonly="readonly">
                    </div>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  姓名
                        <input class="form-control" type="text" value="{{ current_user.teacher.real_name }}"
                               readonly="readonly">
                    </div>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-random" aria-hidden="true"></span>  性别
                        <input class="form-control" type="text" value="{{ current_user.teacher.get_gender_display }}"
                               readonly="readonly">
                    </div>
                </form>
            {% else %}
                <form action="{% url "ems:relate" %} " method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>  工号
                        <input class="form-control" type="text" id="id" name="id" placeholder="请输入工号"
                               required="required">
                    </div>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  校园卡密码
                        <input class="form-control" type="password" id="password" name="password"
                               placeholder="请输入校园卡密码" required="required">
                    </div>
                    <input type="submit" value="确认绑定" class="btn btn-primary">
                </form>
                {% if error_message %}
                    <p class="error_message">{{ error_message }}</p>
                {% endif %}
            {% endif %}
        </div>
        {% else %}
        <div class="panel-heading"><h1>关联学号</h1></div>
        <div class="panel-body">
            {% if current_user.student %}
                <h3>你已绑定至如下信息，如需解绑，请联系管理员</h3>
                <form>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>  学号
                        <input class="form-control" type="text" value="{{ current_user.student.s_id }}"
                               readonly="readonly">
                    </div>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  姓名
                        <input class="form-control" type="text" value="{{ current_user.student.real_name }}"
                               readonly="readonly">
                    </div>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-random" aria-hidden="true"></span>  性别
                        <input class="form-control" type="text" value="{{ current_user.student.get_gender_display }}"
                               readonly="readonly">
                    </div>
                </form>
            {% else %}
                <form action="{% url "ems:relate" %} " method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  学号
                        <input class="form-control" type="text" id="id" name="id" placeholder="请输入学号"
                               required="required">
                    </div>
                    <div class="form-group">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  校园卡密码
                        <input class="form-control" type="password" id="password" name="password"
                               placeholder="请输入校园卡密码" required="required">
                    </div>
                    <input type="submit" value="确认绑定" class="btn btn-primary">
                </form>
                {% if error_message %}
                    <p class="error_message">{{ error_message }}</p>
                {% endif %}
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock %}

ems/templates/ems/subject_teacher.html
{% extends 'ems/base.html' %}

{% block title %}
    课程选择
{% endblock %}

{% block more_head %}
    {% load static %}
    <style>
        .subject-list {
            width: 500px;
        }
        .subject-list li {
            margin-left: 20px;
            font-size: 18px;
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading"><h1>课程选择</h1></div>
        <div class="panel-body">
            <ul class="list-group subject-list">
                {% for subject in subjects %}
                <li class="list-group-item">
                    <a href="{% url 'ems:grade_teacher' subject_id=subject.id%}">{{ subject.id }}  {{ subject.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}