EduMS/urls.py
# 注意所有app的url都要加载到这里
# 即通过include加到path里

from django.contrib import admin
from django.urls import path, include
from django.shortcuts import reverse, redirect


def index(request):
    # 主页，跳转到ems主页
    return redirect(reverse('ems:index'))

urlpatterns = [
    path('admin/', admin.site.urls),  # 管理页面
    path('', index),  # 主页
    path('user/', include('user.urls', namespace='user')),
    path('bbs/', include('bbs.urls', namespace='bbs')),
    path('ems/', include('ems.urls', namespace='ems')),
]

bbs/urls.py
from django.urls import path

from . import views

app_name = 'bbs'
urlpatterns = [
    path('', views.index, name='index'), # 首页
    path('article/<int:page>/', views.article, name='article'),  # 文章列表
    path('publish', views.PublishView.as_view(), name='publish'),  # 发表文章
    path('detail/<int:id>/', views.detail, name='detail'),  # 文章详情
    path('comment/<int:id>/', views.comment, name='comment'),  # 发表评论
]

user/urls.py
# 设置url路径
# 也就是设置网页访问url时对应的处理函数
# 详情可以点进函数里边去看
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),  # 用户主页
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('modify/<str:item>', views.ModifyView.as_view(), name='modify'),  # 修改信息或密码
    path('logout/', views.logout, name='logout'),  # 注销
    path('captcha/', views.graph_captcha, name='captcha'),  # 验证码
    path('getpassword/', views.GetPasswordView.as_view(), name='getPassword'),  # 验证码
]

user/models.py
# orm文件，用于建立模型，之后可以通过django工具映射到数据库中
# 每个model是一个表，每个属性是一个字段，字段的verbose_name即为后台管理界面显示的名字
# CharFiled， IntegerFiled等对应mysql中相应的数据类型
from django.db import models
from datetime import datetime, timedelta
from pytz import timezone


class Role(models.Model):
    # 角色表
    name = models.CharField(max_length=20, verbose_name='角色名')
    desc = models.CharField(max_length=50, verbose_name='角色描述')
    create_time = models.DateTimeField(default=datetime.now, verbose_name='创建时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '角色'
        verbose_name_plural = '角色'


class TeacherValidationCode(models.Model):
    # 教师码表
    code = models.CharField(max_length=10, verbose_name='教师码')
    create_time = models.DateTimeField(default=datetime.now, verbose_name='创建时间')
    expire_days = models.IntegerField(default=7, verbose_name='有效天数')

    class Meta:
        verbose_name = '教师码'
        verbose_name_plural = '教师码'

    def get_expire_time(self):
        # 获取过期时间，也就是创建时间+有效天数
        return self.create_time + timedelta(days=self.expire_days)

    def get_now(self):
        # 获取当前时间（带时区，以便）
        now = datetime.now().replace(tzinfo=timezone('UTC'))
        return now

    def is_validate(self):
        # 确定是否有效，也就是比较现在时间是否大于过期时间
        return self.get_expire_time()>self.get_now()

    def __str__(self):
        return self.code


class PasswordQuestion(models.Model):
    # 密保问题表
    text = models.CharField(max_length=50, unique=True, verbose_name='密保问题文本')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = '密保问题'
        verbose_name_plural = '密保问题'


class User(models.Model):
    # 用户表
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名')
    password = models.CharField(max_length=20, verbose_name='密码')
    # 角色，连接至角色表
    role = models.ForeignKey(Role, on_delete=models.CASCADE, verbose_name='角色')
    # 密保问题，连接至密保问题表
    question = models.ForeignKey(PasswordQuestion, on_delete=models.CASCADE, verbose_name='密保问题')
    # 密保问题答案
    answer = models.CharField(max_length=30, verbose_name='密保问题答案')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = '用户'

user/forms.py
# 表单文件，接收用户从前端界面发送过来的数据，验证数据的有效性
# 每个验证表单都包含一些字段，每个字段包含一些验证器
# 注意这里的字段名必须与前端传入的input的name属性一致
from django.forms import Form, CharField, ValidationError


class LoginForm(Form):
    # 登录信息验证表单
    # 用户名验证（长度，输入必要性）
    # 注意error_message是自定义的验证错误信息，
    # error_message是一个dict，key为验证器的名称， value为对应的验证器验证失败时的信息
    # 注意这里的max_length要与数据库中max_length相匹配，以免出现数据库中的最大存储长度
    # 只有10位，验证通过的数据却有20位这种情况
    username = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的用户名过长（超过20个字符）！',
        'required': '请输入用户名！',
    })
    # 密码验证（长度，输入必要性）
    password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请输入密码！',
    })
    captcha = CharField(max_length=4, required=True, error_messages={
        'max_length': '验证码错误！',
        'required': '请输入验证码！',
    })


class RegisterForm(Form):
    # 注册信息验证表单
    # 用户名验证（长度，输入必要性）
    username = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的用户名过长（超过20个字符）！',
        'required': '请输入用户名！',
    })
    # 密码验证（长度，输入必要性）
    password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请输入密码！',
    })
    # 重复输入密码验证（长度，输入必要性）
    repeat_password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请再次输入密码！',
    })
    # 角色验证（输入必要性）
    role_name = CharField(required=True, error_messages={
        'required': '请选择角色！',
    })
    # 密保问题（输入必要性）
    question_text = CharField(required=True, error_messages={
        'required': '请选择密保问题！',
    })
    # 密保问题答案（输入必要性）
    answer = CharField(max_length=30, required=True, error_messages={
        'max_length': '输入的答案过长（超过30个字符）！',
        'required': '请输入密保问题答案！',
    })
    # 教师码验证（长度）
    teacher_code = CharField(max_length=10, required=False, error_messages={
        'max_length': '输入的教师码过长（超过10个字符）！',
    })

    # 自定义验证器
    # 对于某些字段，简单的长度等基本验证不能满足需求，可以自定义验证器进行验证
    # 函数名必须形如 clean_XXX (XXX即为要验证的字段名，必须与上边定义的名称一致)
    # 只能验证已经定义过的字段，也就是说哪怕你不需要基本验证，也一定要先在上边定义一下名字
    # 验证失败：raise ValidationError(error_message)
    # 验证成功：返回字段名（必须返回，不可省略）
    def clean_repeat_password(self):
        # 这里需要验证一下用户输入的密码与重复确认的密码是否一致
        password = self.cleaned_data['password']
        repeat_password = self.cleaned_data['repeat_password']
        if repeat_password != password:
            raise ValidationError('两次输入的密码不一致！')
        else:
            return repeat_password

    def clean_teacher_code(self):
        # 这里是验证角色为教师时是否输入了教师码，未输入则验证失败
        # 注意并没有限定角色是学生时不可以输入教师码，反正传到后台也不会用到
        teacher_code = self.cleaned_data['teacher_code'].replace(' ', '')
        role_name = self.cleaned_data['role_name']
        if role_name == '教师' and len(teacher_code)==0 :
            raise ValidationError('请输入教师码或更改注册角色！')
        else:
            return teacher_code


class ModifyInfoForm(Form):
    # 修改信息表单验证
    # 目前只有用户名可以改
    username = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的用户名过长（超过20个字符）！',
        'required': '请输入用户名！',
    })


class ModifyPasswordForm(Form):
    # 修改密码表单验证
    old_password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请输入旧密码！',
    })
    new_password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请输入新密码！',
    })
    repeat_new_password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请再次输入新密码！',
    })

    def clean_repeat_new_password(self):
        # 这里验证两次输入的新密码
        # 注意不限制修改后的密码必须与旧密码不同，没有必要
        new_password = self.cleaned_data['new_password']
        repeat_new_password = self.cleaned_data['repeat_new_password']
        if repeat_new_password != new_password:
            raise ValidationError('两次输入的密码不一致！')
        else:
            return repeat_new_password


class GetPasswordForm(Form):
    # 找回密码表单验证

    username = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的用户名过长（超过20个字符）！',
        'required': '请输入用户名！',
    })
    # 密保问题（输入必要性）
    question_text = CharField(required=True, error_messages={
        'required': '请选择密保问题！',
    })
    # 密保问题答案（输入必要性）
    answer = CharField(max_length=30, required=True, error_messages={
        'max_length': '输入的答案过长（超过30个字符）！',
        'required': '请输入密保问题答案！',
    })
    new_password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请输入新密码！',
    })
    repeat_new_password = CharField(max_length=20, required=True, error_messages={
        'max_length': '输入的密码过长（超过20个字符）！',
        'required': '请再次输入新密码！',
    })

    def clean_repeat_new_password(self):
        # 这里验证两次输入的新密码
        # 注意不限制修改后的密码必须与旧密码不同，没有必要
        new_password = self.cleaned_data['new_password']
        repeat_new_password = self.cleaned_data['repeat_new_password']
        if repeat_new_password != new_password:
            raise ValidationError('两次输入的密码不一致！')
        else:
            return repeat_new_password

user/views.py
# 视图函数，处理用户请求的核心函数，与url对应
# 注意它们的装饰器，点进去可以看到装饰器的作用
# 分为两类，一种直接是一个函数，还有一种是一个类，这个类里边可以按照请求方式写不同的函数处理
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.views import View
from .forms import LoginForm, RegisterForm, ModifyInfoForm, ModifyPasswordForm, GetPasswordForm
from .utils import authentic, add_user, login_required, check_username_unique, recoverPassword
from .parameters import *
from django.utils.decorators import method_decorator
from .captcha import Captcha
from io import BytesIO
from .models import PasswordQuestion


@login_required
def index(request, **kwargs):
    # 主页
    # 用户系统没有自己的主页，直接跳转到ems系统的主页
    # redirect: 重定向至另一个url
    # reverse: 根据url的名字获取url
    return redirect(reverse('ems:index'))


class LoginView(View):
    # 登录

    # get方法，直接渲染页面，传入error_message
    # render: 渲染一个html，context为传入html的参数
    def get(self, request, error_message=None):
        if not error_message:
            error_message = request.GET.get('error_message')
        if error_message:
            context = {
                'error_message': error_message
            }
        else:
            context = {}
        return render(request, 'user/login.html', context=context)

    # post方法，处理用户提交的登录信息，根据处理结果做不同的返回
    def post(self, request):
        form = LoginForm(request.POST)  # 将提交的数据先传入表单做个验证，参看表单
        if form.is_valid():
            # 通过表单验证，开始处理
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            captcha = form.cleaned_data['captcha']
            if captcha.lower() != request.session.get(CAPTCHA_TEXT):
                error_message = '验证码错误！'
                return self.get(request, error_message)
            authentication = authentic(username, password)  #验证用户名与密码
            if authentication['code'] == 200:
                # 验证通过，获取登录的user id， 存入session中，以便于后续使用
                user = authentication['data']['user']
                request.session[CURRENT_USER_ID] = user.id
                # 跳转到主页
                return redirect(reverse('user:index'))
            else:
                # 验证不通过，获取错误信息，返回get方法，传入error_message
                error_message= authentication['message']
                return self.get(request, error_message)
        else:
            # 未通过表单验证，从未通过的错误中取出一个，返回get方法，传入error_message
            error_message = form.errors.popitem()[1][0]
            return self.get(request, error_message=error_message)


class RegisterView(View):
    # 注册

    # get方法，直接渲染页面，传入error_message
    def get(self, request, error_message=None):
        questions = PasswordQuestion.objects.all()
        context = {
            'questions': questions
        }
        if error_message:
            context['error_message'] = error_message
        return render(request, 'user/register.html', context=context)

    # post方法，处理用户提交的注册信息，根据处理结果做不同的返回
    def post(self, request):
        form = RegisterForm(request.POST)  # 将提交的数据先传入表单做个验证，参看表单
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            role_name = form.cleaned_data['role_name']
            question_text = form.cleaned_data['question_text']
            answer = form.cleaned_data['answer']
            teacher_code = form.cleaned_data['teacher_code']
            result = add_user(username, password, role_name, question_text, answer, teacher_code)  #添加用户
            if result['code'] == 200:
                # 成功，跳转到登录页面
                return redirect(reverse('user:login') + '?error_message=注册成功！')
            else:
                error_message= result['message']
                return self.get(request, error_message)
        else:
            error_message = form.errors.popitem()[1][0]
            return self.get(request, error_message=error_message)


@method_decorator(login_required, name='dispatch')
class ModifyView(View):
    # 修改信息

    # get方法，直接渲染页面，传入error_message
    # 注意这里的item参数，来自url，用来确定更改的信息类型
    # item为info：修改普通信息（用户名）
    # item为password：修改密码
    def get(self, request, item, error_message=None, **kwargs):
        if error_message:
            context = {
                'error_message': error_message
            }
        else:
            context = {}
        if item == 'info':
            return render(request, 'user/modifyInfo.html', context=context)
        elif item == 'password':
            return render(request, 'user/modifyPassword.html', context=context)

    # post方法，处理用户提交的修改信息，根据处理结果做不同的返回
    def post(self, request, item, **kwargs):
        current_user = kwargs.get(CURRENT_USER)  # 获取当前登录的用户，参看login_required
        error_message = None
        if item == 'info':
            # 修改用户名
            form = ModifyInfoForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                if check_username_unique(username):
                    # 检查是否已被占用
                    current_user.username = username
                    current_user.save()
                    error_message = '修改成功！'
                else:
                    error_message = '用户名已被占用！'
            else:
                error_message = form.errors.popitem()[1][0]
        elif item == 'password':
            # 修改密码
            form = ModifyPasswordForm(request.POST)
            if form.is_valid():
                old_password = form.cleaned_data['old_password']
                new_password = form.cleaned_data['new_password']
                if current_user.password == old_password:
                    # 旧密码匹配，修改密码
                    current_user.password = new_password
                    current_user.save()
                    error_message = '修改成功！'
                else:
                    error_message = '原密码错误！'
            else:
                error_message = form.errors.popitem()[1][0]
        return self.get(request, item, error_message=error_message)


def logout(request, **kwargs):
    # 注销
    # 删除session中的用户id
    del request.session[CURRENT_USER_ID]
    # 跳转到登录页面
    return redirect(reverse('user:login'))


def graph_captcha(request, **kwargs):
    # 验证码生成
    # 通过Captcha生成一张验证码图片，输出为一个HttpResponse
    text,image = Captcha.gene_graph_captcha()
    # 将验证码存入session中
    request.session[CAPTCHA_TEXT] = text.lower()
    out = BytesIO()
    image.save(out,'png')
    out.seek(0)
    resp = HttpResponse(out.read())
    resp.content_type = 'image/png'
    return resp

class GetPasswordView(View):
    # 找回密码

    def get(self, request, error_message=None, **kwargs):
        questions = PasswordQuestion.objects.all()
        context = {
            'questions': questions
        }
        if error_message:
            context['error_message'] = error_message
        return render(request, 'user/getPassword.html', context=context)

    # post方法，处理用户提交的密保信息，根据处理结果做不同的返回
    def post(self, request, **kwargs):
        form = GetPasswordForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            question_text = form.cleaned_data['question_text']
            answer = form.cleaned_data['answer']
            new_password = form.cleaned_data['new_password']
            # 修改密码，参看recoverPassword
            result = recoverPassword(username, question_text, answer, new_password)
            if result['code'] == 200:
                return redirect(reverse('user:login') + '?error_message=修改成功！')
            else:
                error_message = result['message']
                return self.get(request, error_message=error_message)
        else:
            error_message = form.errors.popitem()[1][0]
            return self.get(request, error_message=error_message)

user/templates/user/_head.html
<meta charset="UTF-8">
{% load static %}
<script src="{% static 'user/jquery.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="{% static 'user/bootstrap/bootstrap.min.js' %}"></script>

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'user/_head.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'user/css/base.css' %}">
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block more_head %}{% endblock %}
</head>
<body>
    <div class="top">
        <div class="logo-box">
            <img src="{% static 'user/imgs/university-logo.png' %}" alt="加载中...">
            <img src="{% static 'user/imgs/ems-logo.png' %}" alt="加载中...">
        </div>
    </div>
    <div class="content">
        <div class="left">
            <img src="{% static 'user/imgs/left.png' %}" alt="加载中...">
        </div>
        <div class="right">
            <div class="main-box panel panel-primary">
                {% block main %}

                {% endblock %}
            </div>
        </div>
    </div>
    <div class="foot"></div>
</body>
</html>

user/templates/user/getPassword.html
{% extends 'user/base.html' %}
{% block title %}
    忘记密码
{% endblock %}
{% block more_head %}
    {% load static %}
    <script src="{% static 'user/js/getPassword.js' %}"></script>
{% endblock %}
{% block main %}
    <div class="panel-heading">
        <div class="panel-title">忘记密码/Recover Password</div>
    </div>
    <div class="panel-body">
        <form action="{% url "user:getPassword"%} " method="post">
            {% csrf_token %}
            <div class="form-group">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  用户名
                <input class="form-control" type="text" id="username" name="username" placeholder="请输入用户名"
                       required="required">
            </div>
            <div class="form-group">
            <div class="input-group">
              <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">选择密保问题 <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    {% for question in questions %}
                    <li><a class="question-selector">{{ question.text }}</a></li>
                    {% endfor %}
                </ul>
              </div>
            </div>
            <input type="text" class="form-control" readonly="readonly" value="" name="question_text">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  密保问题答案
                <input class="form-control" type="text" id="answer" name="answer"
                       placeholder="请输入密保问题答案" required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  新密码
                <input class="form-control" type="password" id="password" name="new_password"
                       placeholder="请输入新密码" required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  确认新密码
                <input class="form-control" type="password" id="repeat_password" name="repeat_new_password"
                       placeholder="请再次输入新密码" required="required">
            </div>
            <input type="submit" value="确认修改" class="btn btn-primary">
            <a class="btn btn-primary" href="{% url 'user:login' %}" style="margin-left: 30px">登录</a>
        </form>
        {% if error_message %}
            <p class="error_message">{{ error_message }}</p>
        {% endif %}
    </div>
{% endblock %}

user/templates/user/login.html
{% extends 'user/base.html' %}
{% block title %}
    登录
{% endblock %}
{% block more_head %}
    {% load static %}
    <script src="{% static 'user/js/login.js' %}"></script>
{% endblock %}
{% block main %}
    <div class="panel-heading">
        <div class="panel-title">用户登录/LOGIN</div>
    </div>
    <div class="panel-body">
        <form action="{% url "user:login" %} " method="post">
            {% csrf_token %}
            <div class="form-group">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  用户名
                <input class="form-control" type="text" id="username" name="username" placeholder="请输入用户名"
                       required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  密码
                <input class="form-control" type="password" id="password" name="password"
                       placeholder="请输入密码" required="required">
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="text" id="captcha" name="captcha" placeholder="验证码" style="width: 60%">
                    <span id="-captcha-btn">
                        <img id="captcha-img" class="captcha-img" src="{% url 'user:captcha' %}" alt="加载中">
                    </span>
                </div>
            </div>

            <input type="submit" value="登录" class="btn btn-primary">
            <a href="{% url "user:register" %}" class="btn btn-primary" style="margin-left: 20px">注册</a>
            <a href="{% url "user:getPassword" %}" class="btn btn-primary" style="margin-left: 20px">忘记密码</a>
        </form>
        {% if error_message %}
            <p class="error_message">{{ error_message }}</p>
        {% endif %}
    </div>
{% endblock %}

user/templates/user/modifyInfo.html
{% extends 'user/base.html' %}
{% block title %}
    修改信息
{% endblock %}
{% block more_head %}
    {% load static %}
{% endblock %}
{% block main %}
    <div class="panel-heading">
        <div class="panel-title">修改信息/MODIFY</div>
    </div>
    <div class="panel-body">
        <form action="{% url "user:modify" item='info' %} " method="post">
            {% csrf_token %}
            <div class="form-group">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  用户名
                <input class="form-control" type="text" id="username" name="username" placeholder="{{ current_user.username }}"
                       required="required">
            </div>
            <input type="submit" value="确认修改" class="btn btn-primary">
            <a class="btn btn-primary" href="{% url 'user:index' %}" style="margin-left: 30px">返回首页</a>
        </form>
        {% if error_message %}
            <p class="error_message">{{ error_message }}</p>
        {% endif %}
    </div>
{% endblock %}

{#用戶登錄後進去的修改#}

user/templates/user/modifyPassword.html
{% extends 'user/base.html' %}
{% block title %}
    修改密码
{% endblock %}
{% block more_head %}
    {% load static %}
{% endblock %}
{% block main %}
    <div class="panel-heading">
        <div class="panel-title">修改密码/Modify</div>
    </div>
    <div class="panel-body">
        <form action="{% url "user:modify" item='password' %} " method="post">
            {% csrf_token %}
            <div class="form-group">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  用户名
                <input class="form-control" type="text" id="username" name="username" placeholder="{{ current_user.username }}"
                       readonly="readonly">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  原密码
                <input class="form-control" type="password" id="password" name="old_password"
                       placeholder="请输入原密码" required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  新密码
                <input class="form-control" type="password" id="password" name="new_password"
                       placeholder="请输入新密码" required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  确认新密码
                <input class="form-control" type="password" id="repeat_password" name="repeat_new_password"
                       placeholder="请再次输入新密码" required="required">
            </div>
            <input type="submit" value="确认修改" class="btn btn-primary">
            <a class="btn btn-primary" href="{% url 'user:index' %}" style="margin-left: 30px">返回首页</a>
        </form>
        {% if error_message %}
            <p class="error_message">{{ error_message }}</p>
        {% endif %}
    </div>
{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}
{% block title %}
    注册
{% endblock %}
{% block more_head %}
    {% load static %}
    <script src="{% static 'user/js/register.js' %}"></script>
{% endblock %}
{% block main %}
    <div class="panel-heading">
        <div class="panel-title">用户注册/REGISTER</div>
    </div>
    <div class="panel-body">
        <form action="{% url "user:register" %} " method="post">
            {% csrf_token %}
            <div class="form-group">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>  用户名
                <input class="form-control" type="text" id="username" name="username" placeholder="请输入用户名"
                       required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  密码
                <input class="form-control" type="password" id="password" name="password"
                       placeholder="请输入密码" required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  确认密码
                <input class="form-control" type="password" id="repeat_password" name="repeat_password"
                       placeholder="请再次输入密码" required="required">
            </div>
            <div class="form-group">
            <div class="input-group">
              <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">选择角色 <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a class="role-selector">学生</a></li>
                  <li><a class="role-selector">教师</a></li>
                </ul>
              </div>
            </div>
            <input type="text" class="form-control" readonly="readonly" value="学生" name="role_name">
            </div>
            <div class="form-group">
            <div class="input-group">
              <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">选择密保问题 <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    {% for question in questions %}
                    <li><a class="question-selector">{{ question.text }}</a></li>
                    {% endfor %}
                </ul>
              </div>
            </div>
            <input type="text" class="form-control" readonly="readonly" value="" name="question_text">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  密保问题答案
                <input class="form-control" type="text" id="answer" name="answer"
                       placeholder="请输入密保问题答案" required="required">
            </div>
            <div class="form-group">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>  教师码
                <input class="form-control" type="text" id="teacher_code" name="teacher_code"
                       placeholder="">
            </div>
            <input type="submit" value="注册" class="btn btn-primary">
            <a href="{% url "user:login" %}" class="btn btn-primary" style="margin-left: 20px">登录</a>
        </form>
        {% if error_message %}
            <p class="error_message">{{ error_message }}</p>
        {% endif %}
    </div>
{% endblock %}